[theme]
primaryColor = "#0093D5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#EEF3F8"
textColor = "#003366"
font = "sans serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
